# -*- coding: utf-8 -*-
"""testcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7GEe10caHFkhamxMD1djPz1gLJmrrGq
"""

# ==============================================================================
# Generator 최종 필터 적용 코드 (외부 이미지 업로드 후 적용)
# ==============================================================================

# 0. 필요한 라이브러리 임포트
import os
import torch
import torch.nn as nn # Import nn module
from PIL import Image
from torchvision import transforms
from torchvision.utils import save_image
import torch.nn.functional as F

# Colab/Jupyter 파일 업로드를 위한 임포트
try:
    from google.colab import files
except ImportError:
    files = None
    print("Error: google.colab.files 모듈을 로드할 수 없습니다. Colab/Jupyter 환경에서 실행해주세요.")


# --- 💡 전역 설정 (학습 시 사용된 값 재사용) ---
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
EPS = 5.0 / 255.0  # 학습 시 사용된 L_inf 제약 (최대 노이즈 크기)
TARGET_SIZE = 160 # Generator 입력 크기
# 💡 최적의 체크포인트 경로 설정 (Epoch 43 권장)
FINAL_CHECKPOINT_PATH = "/content/generator_epoch_0046.pth"


# --- 💡 1. U-Net Generator 모델 정의 (이전 코드에서 가져옴) ---
# 이 클래스는 학습 코드 Part 1에 정의되어 있어야 합니다.
# (정의가 없으면 이 셀 실행 시 에러가 발생합니다.)
class ConvBlock(nn.Module):
    def __init__(self, in_c, out_c, kernel_size=3, stride=1, padding=1, norm="bn"):
        super().__init__()
        self.conv = nn.Conv2d(in_c, out_c, kernel_size, stride, padding, bias=False)
        self.norm = nn.BatchNorm2d(out_c) if norm == "bn" else nn.Identity()
        self.relu = nn.ReLU(True)
    def forward(self, x):
        return self.relu(self.norm(self.conv(x)))

class UNetGenerator(nn.Module):
    def __init__(self, in_c=3, out_c=3, base_c=64):
        super().__init__()
        self.enc1 = nn.Sequential(ConvBlock(in_c, base_c), ConvBlock(base_c, base_c))
        self.enc2 = nn.Sequential(nn.AvgPool2d(2), ConvBlock(base_c, base_c*2), ConvBlock(base_c*2, base_c*2))
        self.enc3 = nn.Sequential(nn.AvgPool2d(2), ConvBlock(base_c*2, base_c*4), ConvBlock(base_c*4, base_c*4))
        self.bottle = nn.Sequential(nn.AvgPool2d(2), ConvBlock(base_c*4, base_c*8), ConvBlock(base_c*8, base_c*8), nn.Dropout(0.2))
        self.dec3 = nn.Sequential(nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False), ConvBlock(base_c*8, base_c*4), ConvBlock(base_c*4, base_c*4))
        self.dec2 = nn.Sequential(nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False), ConvBlock(base_c*4, base_c*2), ConvBlock(base_c*2, base_c*2))
        self.dec1 = nn.Sequential(nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False), ConvBlock(base_c*2, base_c), ConvBlock(base_c, base_c))
        self.out_conv = nn.Conv2d(base_c, out_c, kernel_size=1)
        self.tanh = nn.Tanh()
    def forward(self, x):
        e1=self.enc1(x); e2=self.enc2(e1); e3=self.enc3(e2); b=self.bottle(e3)
        d3=self.dec3(b); d2=self.dec2(d3+e3); d1=self.dec1(d2+e2)
        out=self.out_conv(d1+e1); delta_normalized=self.tanh(out)
        return delta_normalized


# --- 💡 2. 필터 적용 함수 (apply_filter) 정의 ---
# 이 함수는 학습 코드 Part 4에 정의되어 있어야 합니다.
def apply_filter(generator_model, original_image_path, eps, output_path=None, target_size=160):
    """
    학습된 Generator를 사용하여 원본 크기 이미지에 필터를 적용하고 저장합니다.
    """
    generator_model.eval()

    img_orig_pil = Image.open(original_image_path).convert("RGB")
    H, W = img_orig_pil.height, img_orig_pil.width
    to_tensor_orig = transforms.ToTensor()

    # 1. Generator 입력용으로 160x160으로 축소
    img_160_pil = img_orig_pil.resize((target_size, target_size), Image.BICUBIC)
    img_160 = to_tensor_orig(img_160_pil).unsqueeze(0).to(DEVICE)

    # 2. 160x160 노이즈 생성
    with torch.no_grad():
        delta_normalized_160 = generator_model(img_160)
        delta_160 = delta_normalized_160 * eps

    # 3. 원본 이미지 로드 및 노이즈를 원본 해상도로 보간
    img_orig = to_tensor_orig(img_orig_pil).unsqueeze(0).to(DEVICE)
    delta_up = F.interpolate(delta_160, size=(H, W), mode='bicubic', align_corners=False)

    # 4. 필터 적용 및 클램핑
    img_adv_full = torch.clamp(img_orig + delta_up, 0.0, 1.0)

    # 5. 저장
    if output_path:
        save_image(img_adv_full.cpu(), output_path)
        print(f"✅ 필터 적용 완료. 저장 경로: {output_path} (해상도: {W}x{H})")

    return img_adv_full

# ==============================================================================
# 3. 실행 로직: 모델 로드 및 파일 업로드/적용
# ==============================================================================

# 3-1. 모델 로드
final_generator = UNetGenerator().to(DEVICE)

try:
    checkpoint = torch.load(FINAL_CHECKPOINT_PATH, map_location=DEVICE)
    final_generator.load_state_dict(checkpoint['model_state_dict'])
    final_generator.eval()
    print(f"✅ Generator 모델이 Epoch 43 체크포인트({FINAL_CHECKPOINT_PATH})로 로드되었습니다.")
except Exception as e:
    print(f"❌ 체크포인트 로드 실패. 경로를 확인하세요: {e}")
    exit()


# 3-2. 파일 업로드 및 필터 적용
if files:
    print("\n[STEP 1/3] 필터를 적용할 외부 이미지 파일을 선택하여 업로드해주세요.")
    uploaded = files.upload()

    if not uploaded:
        print("❌ 업로드된 파일이 없습니다. 프로세스를 중단합니다.")
    else:
        # 업로드된 첫 번째 파일 이름과 경로 설정
        INPUT_FILENAME = list(uploaded.keys())[0]
        INPUT_FILE_PATH = os.path.join("/content/", INPUT_FILENAME)
        OUTPUT_IMAGE_PATH = os.path.join("/content/", f"{INPUT_FILENAME.split('.')[0]}_ADV_FILTERED.png")

        print(f"✅ 파일 '{INPUT_FILENAME}' 로드 완료.")

        # 3-3. 필터 적용 및 결과 다운로드
        print(f"[STEP 2/3] 필터(Generator)를 적용 중입니다. (GPU 사용 안 함)")

        try:
            apply_filter(
                generator_model=final_generator,
                original_image_path=INPUT_FILE_PATH,
                eps=EPS,
                output_path=OUTPUT_IMAGE_PATH,
                target_size=TARGET_SIZE
            )

            print(f"[STEP 3/3] 결과 파일 다운로드를 준비합니다.")
            files.download(OUTPUT_IMAGE_PATH)

        except Exception as e:
             print(f"❌ 필터 적용 중 에러 발생: {e}")